/*
 * Form1.java
 *
 * Created on October 20, 2008, 10:44 PM
 */

package numberxx;

/**
 *
 * @author  kerem
 */
public class Form1 extends javax.swing.JFrame {

    private enum CPU_STATUS {IDLE, BUSY};
    private CPU_STATUS cpuStatus;
    private Thread investigationThread;
    private int number;
    
    /** Creates new form Form1 */
    public Form1() {
        initComponents();
        this.setTitle("Number XX - by Kerem Koseoglu");
        cpuStatus = CPU_STATUS.IDLE;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPhrase = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResult = new javax.swing.JTextArea();
        btnDo = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/numberxx/The-Number-23-50.jpg"))); // NOI18N

        jLabel2.setText("Phrase");

        txtPhrase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhraseActionPerformed(evt);
            }
        });

        jLabel3.setText("Number");

        jLabel4.setText("Algorhytm");

        txtResult.setColumns(20);
        txtResult.setRows(5);
        jScrollPane1.setViewportView(txtResult);

        btnDo.setText("Investigate");
        btnDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoActionPerformed(evt);
            }
        });

        lblStatus.setText("Ready...");
        lblStatus.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel4)
                    .add(jLabel2)
                    .add(jLabel3)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtPhrase, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(txtNumber, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 79, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnDo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)))
                .addContainerGap())
            .add(lblStatus, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(txtPhrase, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(txtNumber, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnDo))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 172, Short.MAX_VALUE)
                        .add(jLabel1))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lblStatus))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void txtPhraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhraseActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtPhraseActionPerformed

private void btnDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoActionPerformed
    
    if (cpuStatus == CPU_STATUS.IDLE) {
        startWorking();
    }
    else {
        stopWorking();
    }
    
    // Get to work!
}//GEN-LAST:event_btnDoActionPerformed

private void startWorking() {
    
    // Check data
    if (getPhrase().length() <= 0) {
        setStatus("Please enter a phrase");
        stopWorking();
        return;
    }
    
    if (txtNumber.getText().length() <= 0) {
        setStatus("Please enter your number");
        stopWorking();
        return;
    }
    
    try {
        number = Integer.parseInt(txtNumber.getText().trim());
    } catch(Exception ex) {
        setStatus("Please enter a valid number");
        stopWorking();
        return;
    }
    
    // Get to work
    btnDo.setText("Cancel");
    setStatus("Working...");
    cpuStatus = CPU_STATUS.BUSY;
    
    investigationThread = new Thread(new InvestigationThread(), "investigationThread");
}

public String getPhrase() {
    String ret = txtPhrase.getText().toUpperCase().trim();
    
    ret = ret.replaceAll("Ğ", "G");
    ret = ret.replaceAll("Ü", "U");
    ret = ret.replaceAll("Ş", "S");
    ret = ret.replaceAll("İ", "I");
    ret = ret.replaceAll("Ö", "O");
    ret = ret.replaceAll("Ç", "C");
    
    return ret;
}

public int getNumber() {
    return number;
}

private void stopWorking() {
        investigationThread.stop();
        btnDo.setText("Investigate");
        cpuStatus = CPU_STATUS.IDLE;
        setStatus("Ready...");
    }
    
public void threadOver(Solution S) {
    stopWorking();
    
    txtResult.setText("");
    for (int m = 0; m < S.getSolution().length; m++) {
        txtResult.append(S.getSolution()[m]);
        txtResult.append("\r\n");
    }
    
}

private void setStatus(String Text) {
    lblStatus.setText(Text);
}

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JTextField txtPhrase;
    private javax.swing.JTextArea txtResult;
    // End of variables declaration//GEN-END:variables

}
